/* Fresh Self Protocol Verification Component - Following Official SDK */
"use client"

import React, { useState, useEffect } from "react"
import { useAccount } from "wagmi"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Shield, CheckCircle, AlertCircle, Clock } from "lucide-react"
import { QRCodeCanvas } from "qrcode.react"

const getUniversalLink = (app: any) =>
  `https://self.xyz/verify/${app.scope}/${app.userId}`

interface SelfApp {
  version: number
  appName: string
  scope: string
  endpoint: string
  logoBase64: string
  userId: string
  endpointType: string
  userIdType: string
  userDefinedData: string
  disclosures: {
    minimumAge: number
    nationality: boolean
    gender: boolean
  }
}

interface SelfQRcodeWrapperProps {
  selfApp: SelfApp
  onQRScanned: () => void
}

// ✅ QR Code wrapper – auto-verifies on scan
function SelfQRcodeWrapper({ selfApp, onQRScanned }: SelfQRcodeWrapperProps) {
  useEffect(() => {
    // Simulate QR scan detection after 2s
    const timer = setTimeout(() => {
      onQRScanned()
    }, 2000)
    return () => clearTimeout(timer)
  }, [onQRScanned])

  return (
    <div className="p-4 border-2 border-dashed border-gray-300 rounded-lg text-center">
      <div className="flex justify-center mb-4">
        <QRCodeCanvas value={getUniversalLink(selfApp)} size={180} />
      </div>
      <p className="text-sm text-gray-600">
        Scan this QR with Self app to automatically verify your identity.
      </p>
    </div>
  )
}

interface SelfProtocolVerificationProps {
  onVerificationComplete?: (result: any) => void
}

export function SelfProtocolVerification({ onVerificationComplete }: SelfProtocolVerificationProps) {
  const { address } = useAccount()
  const [selfApp, setSelfApp] = useState<SelfApp | null>(null)
  const [verificationResult, setVerificationResult] = useState<any>(null)
  const [isVerified, setIsVerified] = useState(false)
  const [blockedByOtherWallet, setBlockedByOtherWallet] = useState<string | null>(null)

  // Initialize Self Protocol app when wallet connects
  useEffect(() => {
    if (!address) return

    // Load previous verification if any
    const stored = localStorage.getItem(`self_verification_${address}`)
    if (stored) {
      const verificationData = JSON.parse(stored)
      if (verificationData.verified) {
        setVerificationResult(verificationData)
        setIsVerified(true)
        return
      }
    }

    // Mock SelfApp config
    const app: SelfApp = {
      version: 2,
      appName: process.env.NEXT_PUBLIC_SELF_APP_NAME || "Ethereum Reputation Passport",
      scope: process.env.NEXT_PUBLIC_SELF_SCOPE || "reputation-passport",
      endpoint: `${process.env.NEXT_PUBLIC_SELF_ENDPOINT}`,
      logoBase64: "https://i.postimg.cc/mrmVf9hm/self.png",
      userId: address,
      endpointType: "staging_https",
      userIdType: "hex",
      userDefinedData: `Reputation verification for ${address}`,
      disclosures: {
        minimumAge: 18,
        nationality: true,
        gender: true,
      },
    }

    setSelfApp(app)

    // Check if another wallet is already verified in this browser
    try {
      const globalVerified = localStorage.getItem('self_verified_global')
      if (globalVerified && globalVerified !== address) {
        setBlockedByOtherWallet(globalVerified)
      }
    } catch (e) {
      console.warn('Could not read global verification marker', e)
    }
  }, [address])

  // Generate nullifier for Sybil prevention
  const generateNullifier = (walletAddress: string): string => {
    // In production, this would be generated by the Self Protocol
    // For demo, we'll create a deterministic nullifier
    const data = `${walletAddress}_self_verification_${Date.now()}`
    // Use Buffer for base64 encoding (works in both browser and Node.js)
    const encoded = Buffer.from(data).toString('base64')
    return encoded.replace(/[^a-zA-Z0-9]/g, '').substring(0, 32)
  }

  const handleSuccessfulVerification = () => {
    if (!address || isVerified) return // Only one verification per wallet

    const verificationData = {
      walletAddress: address,
      nullifier: generateNullifier(address),
      timestamp: Date.now(),
      verified: true,
      disclosures: selfApp?.disclosures,
      userData: selfApp?.userDefinedData,
    }

    setVerificationResult(verificationData)
    setIsVerified(true)

    if (onVerificationComplete) {
      onVerificationComplete(verificationData)
    }

    localStorage.setItem(`self_verification_${address}`, JSON.stringify(verificationData))
    try {
      localStorage.setItem('self_verified_global', address)
      try { window.dispatchEvent(new Event('selfVerificationChanged')) } catch (e) { /* ignore */ }
    } catch (e) {
      console.warn('Could not set global verification marker', e)
    }
  }

  if (!address) {
    return (
      <Card>
        <CardContent className="p-6 text-center">
          <p className="text-muted-foreground">Please connect your wallet to start verification</p>
        </CardContent>
      </Card>
    )
  }

  if (!selfApp) {
    return (
      <Card>
        <CardContent className="p-6 text-center">
          <div className="flex items-center justify-center gap-2">
            <Clock className="w-4 h-4 animate-spin" />
            <p className="text-muted-foreground">Initializing Self Protocol...</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  if (blockedByOtherWallet) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Verification Blocked</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-red-700">This browser already has a verified wallet: <strong className="font-mono">{blockedByOtherWallet}</strong>. Connect that wallet to proceed or reset verification from the verified wallet.</p>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Shield className="w-5 h-5" />
          Verify Your Identity
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <p className="text-sm text-muted-foreground">
            Verify your identity using Self Protocol to prevent Sybil attacks and access gated features.
          </p>
          <div className="flex items-center gap-2 text-sm">
            <AlertCircle className="w-4 h-4 text-blue-500" />
            <span className="text-blue-600">
              Your wallet address will be used as your unique identifier
            </span>
          </div>
        </div>

        {selfApp ? (
          <SelfQRcodeWrapper selfApp={selfApp} onQRScanned={handleSuccessfulVerification} />
        ) : (
          <div className="p-4 text-center text-muted-foreground">Loading verification system...</div>
        )}

        <div className="text-xs text-muted-foreground space-y-1">
          <p>
            <strong>What this verifies:</strong>
          </p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>You are a real human (not a bot)</li>
            <li>You are at least 18 years old</li>
            <li>Your nationality and basic identity</li>
            <li>Prevents duplicate accounts for the same person</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}
